### ISSUE TITLE
[FEAT]: Payment URL SDK API

### ISSUE THREAD

**Issue by MyWay** [getlago/lago-javascript-client#38]
Would it be possible to add payment url generation to the sdk API, too? Currently we can use the JS sdk, but still have to manually fetch that endpoint.

**Comment by ansmonjol** [comment]
Hey @MyWay, can you confirm if the endpoint you refer to is present in our swagger, or not? https://swagger.getlago.com/

This javascript client is autogenerated based on the same open-api schema. If the endpoint you mention is not present here it could explain it's absence

**Comment by vincent-pochet** [comment]
It should be fixed with the last version
