### ISSUE TITLE
[BUG]: Missing wallet_transactions.transaction_status. It's present in DOCS but NOT present in Javascript Client 

### ISSUE THREAD

**Issue by amiranvarov** [getlago/lago-javascript-client#42]
**Describe the bug**
First of all, not a complain. I love what you guys are doing. Just pointing some thing minor, that would be nice to fix. 

While creating wallet transaction I discovered that my Typescript is complaining that there is no transaction_status with Available options: purchased, granted, voided, invoiced. I saw on the Docs, saying that it is present, but in JS SDK it is actually not. 
PS: status and transaction_status are confusing names, it may be good idea to separate them with some more meaningful names.

**To Reproduce**
1. check the docs
2. check the SDK typings

**Expected behavior**
SDK has exact typings listed docs for wallet transaction or any other path

**Screenshots**
<img width="1718" alt="image" src="https://github.com/getlago/lago-javascript-client/assets/41962757/acca0aad-2cdb-4320-984f-9ec7408c0f15">
<img width="1488" alt="image" src="https://github.com/getlago/lago-javascript-client/assets/41962757/20804c9f-b04b-4695-844a-5515ae441df3">

**Support**
Not applicable

**Comment by vincent-pochet** [comment]
Hello @amiranvarov 

Do you still have this issue? 
If so, what is your version of Lago and lago-javascript-client?
